"""empty message

Revision ID: 5a40b06572bf
Revises: 54a34b49bac9
Create Date: 2016-04-28 12:59:12.877941

"""

# revision identifiers, used by Alembic.
revision = '5a40b06572bf'
down_revision = '54a34b49bac9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('input', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'input')
    ### end Alembic commands ###
