"""empty message

Revision ID: ef1dbd3fe501
Revises: None
Create Date: 2016-02-06 23:16:42.245000

"""

# revision identifiers, used by Alembic.
revision = 'ef1dbd3fe501'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terms', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terms', 'description')
    ### end Alembic commands ###
