"""empty message

Revision ID: f20da09c5017
Revises: f7f1a62e1557
Create Date: 2016-05-05 15:19:57.800000

"""

# revision identifiers, used by Alembic.
revision = 'f20da09c5017'
down_revision = 'f7f1a62e1557'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('sha1_hash', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'images', ['sha1_hash'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_column('images', 'sha1_hash')
    ### end Alembic commands ###
