"""empty message

Revision ID: f7f1a62e1557
Revises: 5a40b06572bf
Create Date: 2016-05-01 00:08:19.917000

"""

# revision identifiers, used by Alembic.
revision = 'f7f1a62e1557'
down_revision = '5a40b06572bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('category', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('credit_entity', sa.String(), nullable=True))
    op.add_column('licenses', sa.Column('credit_type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'credit_type')
    op.drop_column('licenses', 'credit_entity')
    op.drop_column('images', 'category')
    ### end Alembic commands ###
